Repository selsa-inube/inubekit-breadcrumbs, pull requests merged in 2024-04, with the labels that each got.

#11 Adjust and export interfaces
  src/Breadcrumbs/BreadcrumbEllipsis/index.tsx
  src/Breadcrumbs/BreadcrumbEllipsis/props.ts
  src/Breadcrumbs/BreadcrumbLink/index.tsx
  src/Breadcrumbs/BreadcrumbLink/props.ts
  src/Breadcrumbs/BreadcrumbMenuLink/index.tsx
  src/Breadcrumbs/BreadcrumbMenuLink/stories/BreadcrumbMenuLink.stories.tsx
  src/Breadcrumbs/index.tsx
  src/Breadcrumbs/props.ts
  src/index.ts
Labels: minor

#12 Publish new version 2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#13 Add auto publish
  .autorc.json
  .github/workflows/auto-release.yml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement

#14 Refactor component (breadcrumbs) so it uses theme from ThemeContext
  package.json
  src/Breadcrumbs/BreadcrumbEllipsis/index.tsx
  src/Breadcrumbs/BreadcrumbLink/index.tsx
Labels: minor

#15 Update workflow in order to avoid merges with failed builds
  .github/workflows/auto-release.yml
Labels: minor
